###########################################################
# GCC template makefile
###########################################################

EXTRAINCDIRS += $(TOP)/common


COMMON_ASRC	 =
COMMON_SRC	 = Lb_Printf.c

ASRC		+= $(COMMON_ASRC)
SRC		+= $(COMMON_SRC)
